version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      args:
        - target=dev
    environment:
      APP_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
